### ISSUE TITLE
인프라 정리

### ISSUE THREAD

**Issue by sjstyle** [benelog/devcenter-bot#43]
핵데이 과제를 위해서 사용하던 ncloud 인스턴스가 12월 8일까지만 사용 가능합니다.

따라서 **다음주 수요일 (12/4) 일괄 반납**을 진행하려 합니다.
서버에 혹시라도 필요한 데이터가 남아있다면 복사해가시기 바랍니다~
(혹시 도움이 필요하시면 필요한 부분을 알려주세요)

**Comment by benelog** [comment]
@sjstyle 
반납되었으면 닫아주시기 바랍니다.

**Comment by sjstyle** [comment]
반납 완료되었습니다~
