### ISSUE TITLE
application.yml의 히스토리 삭제

### ISSUE THREAD

**Issue by benelog** [benelog/devcenter-bot#44]
암호와 token값을 히스토리에서 파악할수 없도록 삭제하고 다시 commit할 예정입니다.

제가 수행할 예정인 작업을 정리하면 아래와 같습니다.

application.yml 파일을 github 저장소 밖으로 복사해둔후 아래 명령을 입력합니다.

```
git filter-branch --tree-filter 'rm -f src/main/resources/application.yml' HEAD
```

그리고 다시 application.yml 을 원래의 위치로 복사해 온 후 아래와 같이 commit/push 합니다.

```
git add .
git commit -m 'application.yml 추가'
git push -f
````

저는 [scm_breeze](https://github.com/scmbreeze/scm_breeze)를 쓰고 있어서 실제 제가 local PC에서 치는 명령어는 아래와 같습니다.

```
gc -am 'application.yml 추가'
gp -f
```

과거 commit history를 바꾸고, 강제 push를 하는 작업이기 때문에 이 작업 이후에는 기존에 받아두었던 소스에서 바로 pull을 할수가 없습니다.

`git reset --hard origin/master` 명령으로 Local master를 origin과 맞춰야 할것으로 예상합니다. 다시 clone을 받는것도 방법입니다.

**Comment by kkyehit** [comment]
옙 비밀번호 바꾸었습니다.
감사합니다.
